name: Node CI

on:
  - push

jobs:
  build:

   
    runs-on: ubuntu-latest

    strategy:
      
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install  
        run: |
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run test

      - name: Test & publish code coverage
        
        uses: paambaati/codeclimate-action@v2.7.4
        
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.7f68ade2da583f583e8b500351dfcf84e10d29fd1e412e8b37787f4e3a0dd77b }}
        with:
          coverageCommand: make test-coverage